/* 
 * Copyright (C) 2002-2012 XimpleWare, info@ximpleware.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 25 13:10:55 PDT 2009
//----------------------------------------------------

package com.ximpleware.extended.xpath;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 22;
  public static final int AND = 23;
  public static final int AXISNAME = 33;
  public static final int NE = 17;
  public static final int LT = 13;
  public static final int OR = 24;
  public static final int DOLLAR = 27;
  public static final int LP = 8;
  public static final int SLASH = 19;
  public static final int RP = 9;
  public static final int NTEST = 31;
  public static final int NAME = 32;
  public static final int AT = 6;
  public static final int LITERAL = 29;
  public static final int GT = 12;
  public static final int LE = 15;
  public static final int SUB = 3;
  public static final int LB = 10;
  public static final int FNAME = 30;
  public static final int RB = 11;
  public static final int COMMA = 7;
  public static final int NUMBER = 28;
  public static final int MULT = 18;
  public static final int EOF = 0;
  public static final int DIV = 21;
  public static final int ADD = 2;
  public static final int UNION = 25;
  public static final int GE = 14;
  public static final int error = 1;
  public static final int DOT = 4;
  public static final int EQ = 16;
  public static final int DDOT = 5;
  public static final int DSLASH = 20;
  public static final int UMINUS = 26;
}

