/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_heartsome_license_Series */

#ifndef _Included_net_heartsome_license_Series
#define _Included_net_heartsome_license_Series
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_heartsome_license_Series
 * Method:    getSeries
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_heartsome_license_Series_getSeries
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif