/**
 * constants.java
 *
 * Version information :
 *
 * Date:2012-4-19
 *
 * Copyright notice :
 */
package net.heartsome.cat.ts.core.bean;

/**
 * @author  jason
 * @version 
 * @since   JDK1.6
 */
public final class Constants {
	
	//========== 涉及到TMX的常量(start) ==========// 
	public static final String TMX_CREATIONTOOL = "Heartsome TM Server";
	public static final String TMX_CREATIONTOOLVERSION = "2.0-1"; //$NON-NLS-1$
	//========== 涉及到TMX的常量(end) ==========// 
	
	//========== 涉及到TBX的常量(start) ==========//	
	/** 术语入库时 martifHeader 子节点 fileDesc 节点的文本 */
	public static final String TBX_ADD_TERM_FILEDESC = "Generated by Heartsome TBX Exporter";	
	public static final String TBX_XCS_DEFAULT = "tbxdefault.xcs";
	//========== 涉及到TBX的常量(end) ==========//
	
	//========== 记忆库匹配算法相关的(start) ==========//	
	public static final String PT_TOOLID = "Auto Fuzzy"; //$NON-NLS-1$
	public static final String TM_TOOLID = "Translation Memory"; //$NON-NLS-1$
	public static final String QT_TOOLID = "Quick Translation"; //$NON-NLS-1$
	public static final String MT_GOOGLE_TOOLID = "Google Translation"; //$NON-NLS-1$
	public static final String MT_BING_TOOLID = "Bing Translation"; //$NON-NLS-1$
	//========== 记忆库匹配算法相关的(start) ==========//	
}
